# Generated by Django 2.2.4 on 2023-08-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criador', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('motivador', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='data de alteração')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preco')),
                ('estoque', models.IntegerField(verbose_name='estoque')),
                ('imagem', models.ImageField(upload_to='produtos', verbose_name='imagem')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
